apiVersion: v1
kind: Service
metadata:
  name: dual-nginx-service
spec:
  selector:
    pod-name: dual-nginx-pod  # Match the labels in your pod
  ports:
    - name: http-port
      protocol: TCP
      port: 80  # Exposed port
      targetPort: 80  # Port the containers are listening on
    - name: custom-http-port
      protocol: TCP
      port: 8081  # Exposed port
      targetPort: 8081  # Port the containers are listening on
  type: LoadBalancer  # Expose the service to the external world

